# https://www.appveyor.com/docs/appveyor-yml
# https://github.com/zeromq/czmq/blob/master/appveyor.yml
# https://github.com/fsprojects/Paket/blob/master/appveyor.yml

version: 1.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

cache:
  - Source\packages -> **\packages.config
  - Tools -> **\packages.config

# https://www.appveyor.com/docs/environment-variables
init:
  - echo Starting building Platron.Client ...
  - echo build version %APPVEYOR_BUILD_VERSION%
  - echo build number %APPVEYOR_BUILD_NUMBER%
  - msbuild /version  

build_script:
  - cmd: release.cmd %APPVEYOR_BUILD_VERSION%

test: off

artifacts:
  - path: out\Release\Packages\*.nupkg

notifications:

  # Email
  - provider: Email
    to:
      - sergior@bk.ru
    subject: 'Platron.Client Build {{status}}'                  
    message: "{{message}}, {{commitId}}, ..."    
    on_build_status_changed: true

  # Slack
#  - provider: Slack
#    incoming_webhook: http://incoming-webhook-url